phrases = [
    "¿Qué hay que hacer hoy?",
    "Vamos que se puede.",
    "Un café y a trabajar",
    "De todas las cosas que llevas puestas, tu actitud es la más importante.",
    "No importa lo despacio que vayas, siempre y cuando no te detengas.",
    "Esfuerzo continuo, no fuerza o inteligencia. Es la clave para liberar nuestro potencial.",
    "El éxito no se logra sólo con cualidades especiales. Sobre todo un trabajo de constancia, de método y de organización.",
    "No esperes que las oportunidades lleguen solas. Tienes que hacer que ocurra.",
    "La disciplina es el ingrediente más importante del éxito.",
    "La motivación nos impulsa a empezar un hábito. El hábito, nos permite continuar.",
    "Dá siempre tu 100%. Pon todo lo que eres en lo mínimo que hagas.",
    "No busques los errores, busca la solución.",
    "Tu gran oportunidad puede ser justo donde te encuentras ahora.",
    "Quien no ama su trabajo, aún trabajando todo el día, será un desocupado.",
    "Si crees que puedes, ya estás a medio camino.",
]